### ISSUE TITLE
New Sandbox

### ISSUE THREAD

**Issue by FireFreeze105** [kapi1525/NoiseExtension#17]
Can i run new noise sandbox in Clickteam without Plus version? When i tried it, app just closing

**Comment by kapi1525** [comment]
Works fine without 2.5 plus for me, make sure you have the latest fusion installed (build 295.10)

**Comment by FireFreeze105** [comment]
i found problem. What this? This gives error and crash app, clickteam dont have this comand
![image](https://github.com/kapi1525/NoiseExtension/assets/81075325/f9ec429f-6c81-4d4f-80e9-2b7ae5166fbd)
it translates like "Player name", but this comand(and comand uncorrect) gives string, but event asking for value and give error
![image](https://github.com/kapi1525/NoiseExtension/assets/81075325/c736619a-0c64-4635-93d7-5b5104d00b66)

**Comment by kapi1525** [comment]
![](https://github.com/kapi1525/NoiseExtension/assets/67241550/ceed2fe5-79b6-40c6-b0e8-684136722fa0)
![](https://github.com/kapi1525/NoiseExtension/assets/67241550/c89091c4-1c33-48cd-9b43-d78f300c0f55)
It should be 'fixed value of last created object'.

**Comment by FireFreeze105** [comment]
oh, ok, i try it later, thank you

**Comment by FireFreeze105** [comment]
it works
![image](https://github.com/kapi1525/NoiseExtension/assets/81075325/39d22c28-3616-4aa4-bc3f-f584b44dbc57)
