### ISSUE TITLE
Why it not works?

### ISSUE THREAD

**Issue by FireFreeze105** [kapi1525/NoiseExtension#19]
I do it
![image](https://github.com/kapi1525/NoiseExtension/assets/81075325/a11d5dc6-bef2-46a6-a6e3-2aa14d27936d)
and get it
![image](https://github.com/kapi1525/NoiseExtension/assets/81075325/cf738200-821a-4c03-9aa5-0f21a6387495)

**Comment by kapi1525** [comment]
fixed in https://github.com/kapi1525/NoiseExtension/commit/b33f2ce9a88c2f77f5f790e0fd2055dfb1e1f8ff
will release new version with those fixes in a few days.
for now you can download a test build here: <https://github.com/kapi1525/NoiseExtension/actions/runs/7393336826/artifacts/1144458992>
